services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: blog_development
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: blogpassword #zmienic na task
    volumes:
      - ../db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ../application:/home/hosting/app
    environment:
      DATABASE_URL: postgres://postgres:blogpassword@db:5432/blog_development
      DJANGO_SETTINGS_MODULE: application.settings
    depends_on:
      - db
    stdin_open: true
    tty: true
